apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio2024supermariodockerproject-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio2024supermariodockerproject
  template:
    metadata:
      labels:
        app: portfolio2024supermariodockerproject
    spec:
      containers:
      - image: mkogon231/portfolio2024-supermario-docker-project:2
        name: supermariogame-container
        ports:
        - containerPort: 8080
 
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio2024supermariodockerproject-service
spec:
  selector:
    app: portfolio2024supermariodockerproject
  ports:
  - protocol: TCP
    port: 8600  # <-- Change this line to your desired port
    targetPort: 8080
  type: LoadBalancer
