name: "Run Container Scan on Super Mario Docker Image with Quality Gate"
 
# on:
#   push:
#     branches:
#       - main
 
env:
  VERSION: $(( $(cat version.txt) + 1 ))
  
jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest	
 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
        
      - name: Get Docker Image from Docker Hub
        run: |
          docker pull docker.io/mkogon231/portfolio2024-supermario-docker-project:${{ env.VERSION }}
          docker save -o portfolio2024supermariodockerproject.tar docker.io/mkogon231/portfolio2024-supermario-docker-project:${{ env.VERSION }}
     
      - name: Run Trivy vulnerability scanner in tarball mode
        uses: aquasecurity/trivy-action@master
        with:
#          input: /c/portfolio/devsecops/integrate-sonarqube-with-quality-gates-in-devsecops-for-mario-repo/portfolio2024supermariodockerproject.tar
          input: /github/workspace/portfolio2024supermariodockerproject.tar
          exit-code: '0'
          severity: 'CRITICAL,HIGH'
